"""empty message

Revision ID: 0003
Revises: 0002
Create Date: 2022-08-17 13:07:28.891651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_open_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['exchange_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['exchange_wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('_account_currency_unique', 'exchange_balance', ['account_id', 'currency'])
    op.add_column('exchange_closed_orders', sa.Column('sell_order_id', sa.Integer(), nullable=True))
    op.drop_constraint('exchange_closed_orders_sell_transaction_id_fkey', 'exchange_closed_orders', type_='foreignkey')
    op.create_foreign_key(None, 'exchange_closed_orders', 'exchange_orders', ['sell_order_id'], ['id'], ondelete='CASCADE')
    op.drop_column('exchange_closed_orders', 'sell_transaction_id')
    op.add_column('exchange_proxy_orders', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('exchange_proxy_orders', sa.Column('amount', sa.Float(), nullable=True))
    op.drop_constraint('exchange_proxy_orders_transaction_id_fkey', 'exchange_proxy_orders', type_='foreignkey')
    op.create_foreign_key(None, 'exchange_proxy_orders', 'exchange_orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_column('exchange_proxy_orders', 'transaction_id')
    op.drop_column('exchange_proxy_orders', 'shares')
    op.add_column('users', sa.Column('currency', sa.String(length=5), nullable=True))
    op.drop_column('exchange_balance', 'update_date')
    op.add_column('exchange_balance', sa.Column('update_date', sa.DateTime(), nullable=False))
    op.drop_column('exchange_orders', 'value_date')
    op.add_column('exchange_orders', sa.Column('value_date', sa.DateTime(), nullable=False))
    op.drop_column('exchange_transactions', 'value_date')
    op.add_column('exchange_transactions', sa.Column('value_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'currency')
    op.add_column('exchange_proxy_orders', sa.Column('shares', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('exchange_proxy_orders', sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('exchange_proxy_orders_transaction_id_fkey', 'exchange_proxy_orders', 'exchange_orders', ['transaction_id'], ['id'], ondelete='CASCADE')
    op.drop_column('exchange_proxy_orders', 'amount')
    op.drop_column('exchange_proxy_orders', 'order_id')
    op.add_column('exchange_closed_orders', sa.Column('sell_transaction_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('exchange_closed_orders_sell_transaction_id_fkey', 'exchange_closed_orders', 'exchange_orders', ['sell_transaction_id'], ['id'], ondelete='CASCADE')
    op.drop_column('exchange_closed_orders', 'sell_order_id')
    op.drop_constraint('_account_currency_unique', 'exchange_balance', type_='unique')
    op.drop_table('exchange_open_orders')
    # ### end Alembic commands ###
