"""empty message

Revision ID: 0004
Revises: 0003
Create Date: 2023-01-19 15:24:24.721251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accounts_name_key', 'accounts', type_='unique')
    op.create_unique_constraint('_name_user_id_unique', 'accounts', ['name', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_name_user_id_unique', 'accounts', type_='unique')
    op.create_unique_constraint('accounts_name_key', 'accounts', ['name'])
    # ### end Alembic commands ###
