"""empty message

Revision ID: 0005
Revises: 0004
Create Date: 2024-03-27 13:38:39.939518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stock_transactions_external_id_key', 'stock_transactions', type_='unique')
    op.create_unique_constraint('_account_id_external_id', 'stock_transactions', ['account_id', 'external_id'])
    op.drop_constraint('watchlists_name_key', 'watchlists', type_='unique')
    op.create_unique_constraint('_watchlist_user_id_name_unique', 'watchlists', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_watchlist_user_id_name_unique', 'watchlists', type_='unique')
    op.create_unique_constraint('watchlists_name_key', 'watchlists', ['name'])
    op.drop_constraint('_account_id_external_id', 'stock_transactions', type_='unique')
    op.create_unique_constraint('stock_transactions_external_id_key', 'stock_transactions', ['external_id'])
    # ### end Alembic commands ###
