version: '3.8'

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: api
    command: python app.py run -h 0.0.0.0
    volumes:
      - ./app/api:/usr/src/
      - ./app/config:/usr/src/config
      - ./app/models:/usr/src/models
      - ./VERSION:/usr/VERSION
    environment:
      - FLASK_ENV=development
      - BACKEND_SETTINGS=config.full
#      - PYTHON_FILE=app.py
#      - PYTHON_ARGS="run -h 0.0.0.0:${PORT}"
    networks:
      - api_bridge
    restart: always
    depends_on:
      - db
      - redis

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: backend
    command: python worker.py
    volumes:
      - ./app/backend:/usr/src/
      - ./app/config:/usr/src/config
      - ./app/models:/usr/src/models
    environment:
      - BACKEND_SETTINGS=config.full
      - PYTHON_FILE=worker.py
      - PYTHON_ARGS=""
    networks:
      - api_bridge
    restart: always
    deploy:
      replicas: 1
    depends_on:
      - redis
      - db

  migrate:
    image: queds_api
    command: bash -c "cd models && alembic upgrade head"
    volumes:
      - ./app/config:/usr/src/config
      - ./app/models:/usr/src/models
    environment:
      - BACKEND_SETTINGS=config.full
    networks:
      - api_bridge
    depends_on:
      - db
      - api

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_APP_BACKEND_URL=/api
        - VITE_APP_IS_DEMO=false
    command: npm run dev
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    networks:
      - api_bridge
    depends_on:
      - db
      - api

  nginx:
    image: nginx
    volumes:
      - ./nginx_template.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - 6060:80
    depends_on:
      - backend
      - frontend
    networks:
      - api_bridge

  redis:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    logging:
      driver: none
    networks:
      - api_bridge

  db:
    image: timescale/timescaledb:2.18.2-pg16
    restart: always
    environment:
      POSTGRES_DB: queds
      POSTGRES_USER: queds_user
      POSTGRES_PASSWORD: Kbh85n7M6Fxo
    volumes:
      - users_data:/var/lib/postgresql/data/
    networks:
      - api_bridge
    ports:
      - 5432:5432

networks:
  api_bridge:
    driver: bridge

volumes:
  users_data:
