"""empty message

Revision ID: 0002
Revises: 
Create Date: 2022-07-19 23:36:02.799730

"""
from alembic import op
import sqlalchemy as sa
from models.fixtures import upgrade_fixtures


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # create entities
    from models.system import User, Entity
    entities = [{"name": "Degiro", "type": Entity.Type.BROKER, "active": True},
                {"name": "ClickTrade", "type": Entity.Type.BROKER, "active": True},
                {"name": "IB", "type": Entity.Type.BROKER, "active": True},
                {"name": "October", "type": Entity.Type.CROWD, "active": True},
                {"name": "BBVA", "type": Entity.Type.BANK, "active": True},
                {"name": "Bitstamp", "type": Entity.Type.EXCHANGE, "active": True},
                {"name": "Kraken", "type": Entity.Type.EXCHANGE, "active": True},
                {"name": "Bittrex", "type": Entity.Type.EXCHANGE, "active": True},
                {"name": "Binance", "type": Entity.Type.EXCHANGE, "active": True}]

    print("Creating entities")
    table = sa.table('entities',
                           sa.column('type', sa.Integer),
                           sa.column('name', sa.String),
                           sa.column('active', sa.Integer)
                           )
    op.bulk_insert(table, entities)

    upgrade_fixtures()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("""truncate entities cascade;"""))
    # ### end Alembic commands ###
