"""empty message

Revision ID: 0002
Revises: 
Create Date: 2025-11-19 11:25:58.479160

"""
from alembic import op
import sqlalchemy as sa
from models.fixtures import upgrade_fixtures


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    upgrade_fixtures()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("""truncate entities cascade;"""))
    # ### end Alembic commands ###
