"""empty message

Revision ID: 0006
Revises: 0005
Create Date: 2024-04-05 11:43:52.449438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('market', sa.String(length=50), nullable=True))
    op.add_column('tickers', sa.Column('previous_ticker', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickers', 'tickers', ['previous_ticker'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickers', type_='foreignkey')
    op.drop_column('tickers', 'previous_ticker')
    op.drop_column('tickers', 'market')
    # ### end Alembic commands ###
