"""empty message

Revision ID: 0007
Revises: 0006
Create Date: 2024-08-06 12:34:50.355018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reverse_split_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buy_transaction_id', sa.Integer(), nullable=True),
    sa.Column('sell_transaction_id', sa.Integer(), nullable=True),
    sa.Column('ratio', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('new_shares', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buy_transaction_id'], ['stock_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sell_transaction_id'], ['stock_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reverse_split_orders')
    # ### end Alembic commands ###
