"""empty message

Revision ID: 0009
Revises: 0008
Create Date: 2025-02-21 22:37:47.478850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_ticker_isin_status_unique', 'tickers', type_='unique')
    op.create_unique_constraint('_ticker_isin_unique', 'tickers', ['ticker', 'isin'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_ticker_isin_unique', 'tickers', type_='unique')
    op.create_unique_constraint('_ticker_isin_status_unique', 'tickers', ['ticker', 'isin', 'status'])
    # ### end Alembic commands ###
