"""empty message

Revision ID: 0010
Revises: 0009
Create Date: 2025-03-21 19:31:53.185064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_transactions', 'value_date',
                    existing_type=sa.Date(),
                    type_=sa.TIMESTAMP(),
                    existing_nullable=False
                    )
    op.add_column('stock_open_orders', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('stock_open_orders', sa.Column('currency_rate', sa.Float(), nullable=True))
    op.create_unique_constraint('_exchange_account_id_external_id', 'exchange_orders', ['account_id', 'external_id'])
    op.drop_constraint('exchange_orders_external_id_key', 'exchange_orders', type_='unique')
    op.drop_constraint('exchange_transactions_external_id_key', 'exchange_transactions', type_='unique')
    op.create_unique_constraint('_exchange_transaction_account_id_external_id', 'exchange_transactions', ['account_id', 'external_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_exchange_transaction_account_id_external_id', 'exchange_transactions', type_='unique')
    op.create_unique_constraint('exchange_transactions_external_id_key', 'exchange_transactions', ['external_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('exchange_orders_external_id_key', 'exchange_orders', ['external_id'])
    op.drop_constraint('_exchange_account_id_external_id', 'exchange_orders', type_='unique')
    op.drop_column('stock_open_orders', 'currency_rate')
    op.drop_column('stock_open_orders', 'price')
    op.alter_column('stock_transactions', 'value_date',
        existing_type=sa.TIMESTAMP(),
        type_=sa.Date(),
        existing_nullable=False
    )
