FROM python:3.9
# to be used by heroku for demo page

COPY . /usr/src
COPY models /user/src/models
COPY config /user/src/config
COPY dist /user/src/dist

WORKDIR /usr/src

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install python dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# gunicorn
#CMD ["gunicorn", "--config", "gunicorn-cfg.py", "run:app"]
CMD python app.py run -h 0.0.0.0:${PORT}
